---
development:
  cloud_name: dgqbv7rnu
  api_key: '986181877915179'
  api_secret: 4-B3_tGTmKsx-r1TX-kveVZoulA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dgqbv7rnu
  api_key: '986181877915179'
  api_secret: 4-B3_tGTmKsx-r1TX-kveVZoulA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dgqbv7rnu
  api_key: '986181877915179'
  api_secret: 4-B3_tGTmKsx-r1TX-kveVZoulA
  enhance_image_tag: true
  static_image_support: false
