# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2a269d704e60a7c4b409c8ca32d8acc2b7ea4a20febd5929dd379d89969e8a5fa35ca8f3e230c845b8318feab4be3c7e964ceece26e97bdcf158b6173978d59

test:
  secret_key_base: 90c8b695fd07ff5cdd01855c7c2493ae7323acd2938fc4826c53c19bf651b541542bbc4eb2c357d0be47b349ae0d826f6d1f52dfa70f61a1abe67c52d5e65afd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
